"""add_threat_intel_and_evidence_models

Revision ID: 6cc17a9a8238
Revises: 9ce49fe9b5e8
Create Date: 2026-06-29 13:51:51.829934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc17a9a8238'
down_revision: Union[str, None] = '9ce49fe9b5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('ioc_id', sa.UUID(), nullable=True),
    sa.Column('mitre_technique_id', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['normalized_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_investigation_id'), 'evidence', ['investigation_id'], unique=False)
    op.create_index('ix_evidence_org_inc_inv', 'evidence', ['organization_id', 'incident_id', 'investigation_id'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ioc_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('provider_version', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('weighted_confidence', sa.Float(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('normalized_response', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_ioc_id'), 'threat_intelligence', ['ioc_id'], unique=False)
    op.create_index('ix_ti_ioc_provider', 'threat_intelligence', ['ioc_id', 'provider_name'], unique=False)
    op.create_table('evidence_ti_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('threat_intel_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_intel_id'], ['threat_intelligence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_ti_references_evidence_id'), 'evidence_ti_references', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_ti_references_threat_intel_id'), 'evidence_ti_references', ['threat_intel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_ti_references_threat_intel_id'), table_name='evidence_ti_references')
    op.drop_index(op.f('ix_evidence_ti_references_evidence_id'), table_name='evidence_ti_references')
    op.drop_table('evidence_ti_references')
    op.drop_index('ix_ti_ioc_provider', table_name='threat_intelligence')
    op.drop_index(op.f('ix_threat_intelligence_ioc_id'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index('ix_evidence_org_inc_inv', table_name='evidence')
    op.drop_index(op.f('ix_evidence_investigation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
