"""add_correlation_and_graph_models

Revision ID: 72d6e731a19f
Revises: 6cc17a9a8238
Create Date: 2026-06-29 14:03:42.519807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d6e731a19f'
down_revision: Union[str, None] = '6cc17a9a8238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('correlation_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_correlation_group_inv', 'correlation_groups', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_correlation_groups_investigation_id'), 'correlation_groups', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_correlation_groups_organization_id'), 'correlation_groups', ['organization_id'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('node_value', sa.String(length=500), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investigation_id', 'node_type', 'node_value', name='uix_graph_node_inv_type_val')
    )
    op.create_index('ix_graph_nodes_inv_type', 'graph_nodes', ['investigation_id', 'node_type'], unique=False)
    op.create_index(op.f('ix_graph_nodes_investigation_id'), 'graph_nodes', ['investigation_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'relationship_type', name='uix_graph_edge_src_tgt_type')
    )
    op.create_index(op.f('ix_graph_edges_investigation_id'), 'graph_edges', ['investigation_id'], unique=False)
    op.create_index('ix_graph_edges_source', 'graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False)
    op.create_index('ix_graph_edges_target', 'graph_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False)
    op.create_table('correlation_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correlation_group_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['correlation_group_id'], ['correlation_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_evidence_correlation_group_id'), 'correlation_evidence', ['correlation_group_id'], unique=False)
    op.create_index(op.f('ix_correlation_evidence_evidence_id'), 'correlation_evidence', ['evidence_id'], unique=False)
    op.add_column('investigations', sa.Column('investigation_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'investigation_summary')
    op.drop_index(op.f('ix_correlation_evidence_evidence_id'), table_name='correlation_evidence')
    op.drop_index(op.f('ix_correlation_evidence_correlation_group_id'), table_name='correlation_evidence')
    op.drop_table('correlation_evidence')
    op.drop_index(op.f('ix_graph_edges_target_node_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_target', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_source_node_id'), table_name='graph_edges')
    op.drop_index('ix_graph_edges_source', table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_investigation_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_graph_nodes_investigation_id'), table_name='graph_nodes')
    op.drop_index('ix_graph_nodes_inv_type', table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_correlation_groups_organization_id'), table_name='correlation_groups')
    op.drop_index(op.f('ix_correlation_groups_investigation_id'), table_name='correlation_groups')
    op.drop_index('ix_correlation_group_inv', table_name='correlation_groups')
    op.drop_table('correlation_groups')
    # ### end Alembic commands ###
