"""add_chat_model

Revision ID: 92b50179f5de
Revises: 72d6e731a19f
Create Date: 2026-06-29 14:16:29.100351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b50179f5de'
down_revision: Union[str, None] = '72d6e731a19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_chat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigation_chat_inv_date', 'investigation_chat', ['investigation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigation_chat_investigation_id'), 'investigation_chat', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_chat_investigation_id'), table_name='investigation_chat')
    op.drop_index('ix_investigation_chat_inv_date', table_name='investigation_chat')
    op.drop_table('investigation_chat')
    # ### end Alembic commands ###
