"""add_investigation_models

Revision ID: 9ce49fe9b5e8
Revises: 4435bed414cf
Create Date: 2026-06-29 13:37:21.253619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce49fe9b5e8'
down_revision: Union[str, None] = '4435bed414cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('file_record_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('iocs_extracted', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_record_id'], ['incident_files.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_file_record_id'), 'investigations', ['file_record_id'], unique=False)
    op.create_index(op.f('ix_investigations_incident_id'), 'investigations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_investigations_organization_id'), 'investigations', ['organization_id'], unique=False)
    op.create_table('normalized_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_provider', sa.String(length=255), nullable=True),
    sa.Column('event_action', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('destination_ip', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('host_name', sa.String(length=255), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_normalized_events_org_inc_inv', 'normalized_events', ['organization_id', 'incident_id', 'investigation_id'], unique=False)
    op.create_index('ix_normalized_events_timestamp', 'normalized_events', ['timestamp'], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['normalized_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iocs_org_inc_inv', 'iocs', ['organization_id', 'incident_id', 'investigation_id'], unique=False)
    op.create_index('ix_iocs_type_value', 'iocs', ['ioc_type', 'value'], unique=False)
    op.create_index('ix_iocs_unique_value_per_inv', 'iocs', ['investigation_id', 'ioc_type', 'value'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_iocs_unique_value_per_inv', table_name='iocs')
    op.drop_index('ix_iocs_type_value', table_name='iocs')
    op.drop_index('ix_iocs_org_inc_inv', table_name='iocs')
    op.drop_table('iocs')
    op.drop_index('ix_normalized_events_timestamp', table_name='normalized_events')
    op.drop_index('ix_normalized_events_org_inc_inv', table_name='normalized_events')
    op.drop_table('normalized_events')
    op.drop_index(op.f('ix_investigations_organization_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_incident_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_file_record_id'), table_name='investigations')
    op.drop_table('investigations')
    # ### end Alembic commands ###
